### PR TITLE
NetCore 3.1 Migration

### PR DESCRIPTION
**Pull request by UmutComlekci**
[MahApps.Metro v2.0](https://mahapps.com/docs/guides/migration-to-v2.0) released and I start to migrate all projects to Net Core 3.1. It's still buggy and has some deficiencies but with help of contributors, in a short time we can complete migration.

### CODE REVIEW

**Comment by BornToBeRoot** [comment]
Thanks for your work and your pr. I would like to migrate to .net core 3.1 and later to .NET 5

I've been busy for the past two week, so sorry for the late reply :) 

I started to look at your code but currently stucked here, when i try to run the solution: 

```
System.Windows.Markup.XamlParseException
  HResult=0x80131501
  Message='Initialization of 'System.Windows.Setter' threw an exception.' Line number '7' and line position '10'.
  Source=PresentationFramework
  StackTrace:
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at NETworkManager.App.InitializeComponent() in D:\GitHub_Repositories\NETworkManager\Source\NETworkManager\App.xaml:line 1

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
ArgumentNullException: Value cannot be null. (Parameter 'property')
```

Any ideas?

**Comment by UmutComlekci** [comment]
There is no problem for delay and it's makes sense to upgrade with .Net 5.

In the other hand, yes I know when you debug to project, it's throw an exception immediately. This exception might be happening to wrong CSPROJ configuration for `Resources/Styles/*.xaml` files. I'm only add `Resources\Styles\WindowStyles.xaml` file for testing, most probably we must add the others too.

**Comment by BornToBeRoot** [comment]
I got it running by removing `EnableDWMDropShadow` in the Window style.

But there are a lot of resource keys that need to be updated (MahApps v2) and there  are some bugs that need to fixed for .net-core.

**Comment by UmutComlekci** [comment]
With documentation of [MahApps Migration to v2.0](https://mahapps.com/docs/guides/migration-to-v2.0), I updated too many resource keys but as you know we need to fix much more

**Comment by BornToBeRoot** [comment]
I have some custom themes who needs to be fixed, but most of them worked with MahApps 2

I created an issue to document the migration: #309

**Comment by BornToBeRoot** [comment]
The new settings view:
image

I had to remove 2 custom designs 😢 

There is an option to generate themes at runtime... but i have to fix the light design first...

**Comment by BornToBeRoot** [comment]
I moved the PR to https://github.com/BornToBeRoot/NETworkManager/tree/net5-develop

Since .NET-5.0 preview 8 is feature complete and will be released this year, i will migrate to it.

There are some issues from netcore 3.1 which are fixed now and i can migrate to webview2 wpf with edge can.

There are still some issues which need to be fixed before the first release.


if you want to help, let me know :)

**Pull request closed without merging**
