### PR TITLE
Update Strings.sl-SI.resx

### PR DESCRIPTION
**Pull request by JadranR**
Updated 21.11.2022
Best Regards,
Jadran

Fixes #{Replace this with the issue number}

**Please provide some details about this pull request:**
-
-
-

---

**By submitting this pull request, I confirm the following:**

- [x] I have read and understood the [contributing guidelines](https://github.com/BornToBeRoot/NETworkManager/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/BornToBeRoot/NETworkManager/blob/main/CODE_OF_CONDUCT.md).
- [ ] I have have added my name, username or email to the [contributors](https://github.com/BornToBeRoot/NETworkManager/blob/main/Contributors.md) list or don't want to.
- [x] The code or resource is compatible with the [GNU General Public License v3.0](https://github.com/BornToBeRoot/NETworkManager/blob/main/LICENSE).

### CODE REVIEW

**Comment by JadranR** [comment]
Updated Sloveian translation, 21.11.2022.
Best Regards,
Jadran

**Comment by BornToBeRoot** [comment]
@JadranR kann you please do it via Transifex.
https://explore.transifex.com/BornToBeRoot/NETworkManager/

**Comment by JadranR** [comment]
Hi,
Yes,
I can.
Please, delete Slovenian translation from other translation tools.

Big thanks.
Jadran

V V tor., 22. nov. 2022 ob 09:11 je oseba BornToBeRoot <
***@***.***> napisala:

**Comment by BornToBeRoot** [comment]
Thanks! I saw that you updated the translation and it was already merged.

"Please, delete Slovenian translation from other translation tools."
Besides transifex there are no other translation tools. But the files are stored and updated in this repo

**Pull request closed without merging**
