### PR TITLE
Feature: Implemented IP Whois Queries to Ripe database #1522

### LINKED ISSUE #1522: [New App/Extension] Whois IP
Could you create the possability to do a whois query for an IP from RIPE?

### PR DESCRIPTION
**Pull request by Sahnreis**
**Please provide some details about this pull request:**
- added Whois Settingspage to toggle between normal whois and IP whois to ripe
- implemented Ripe Api Client
- updated WhoisView to fit new results

Fixes #1522 

**ToDo:**

- [ ] Update [documentation](https://github.com/BornToBeRoot/NETworkManager/tree/main/docs/Documentation) to reflect this changes
- [ ] Update [changelog](https://github.com/BornToBeRoot/NETworkManager/tree/main/docs/Changelog) to reflect this changes

---

**By submitting this pull request, I confirm the following:**

- [x] I have read and understood the [contributing guidelines](https://github.com/BornToBeRoot/NETworkManager/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/BornToBeRoot/NETworkManager/blob/main/CODE_OF_CONDUCT.md).
- [x] I have have added my name, username or email to the [contributors](https://github.com/BornToBeRoot/NETworkManager/blob/main/Contributors.md) list or don't want to.
- [x] The code or resource is compatible with the [GNU General Public License v3.0](https://github.com/BornToBeRoot/NETworkManager/blob/main/LICENSE).

### CODE REVIEW

**Comment by BornToBeRoot** [comment]
@Sahnreis thanks! I'll have a look at it the next few days...

**Comment by BornToBeRoot** [comment]
@Sahnreis i found some input validation errors that I can fix. I would also use a dropdown list to choose between domain and IP address lookup instead of the toggle switch in the settings.

The RIPE API only returns data from IP addresses assigned to them. But there are 4 more regional internet registries... arin, apnic, lacnic, afrinic (https://www.iana.org/assignments/ipv4-address-space/ipv4-address-space.xhtml). I am not sure if they provide an API to query... or maybe a third-party api which provides all data.

image

**Comment by Sahnreis** [comment]
@BornToBeRoot thank you for your feedback. i will have a look at the possible options regarding the other RIRs and propose a solution at some point this week.

**Comment by Sahnreis** [comment]
hey @BornToBeRoot, i had a look into the RIR problem and concluded, that we will face some issues trying to implement all RIRs manually. 
1. not all RIRs provide a public available API - or they dont have a localized documantation, making an implementation kinda stressful.
2. the  APIs return their data in different formats
3. if you dont want to ask all providers at once to find the one that is in charge of a specific range we would need to figure out, which range is managed by which RIR. There are tables on the internet(they are often not up to date and we would need to "copy" them to code and keep them updated) or we go for iana "whois service" - which does not have a public api and needs to be operated through their webinterface - and a headless browser automation in the background feels a little bit "hacky" tbh

therefore, i would opt for "https://ipinfo.io/products/whois-api" - they provide an API/C# lib and can take care of all the problems that come with a manuall implementation. they also offer a free tier(50k requests). If we would go with this solution, it would be necessary to enter/store the API KEY for the service. 

which solution do you prefer? manual implementation or ipinfo.io?

**Comment by BornToBeRoot** [comment]
@Sahnreis Sorry for the late reply - I've been very busy the last few days.

I would like to not use an API with a key, because you can't store the key securely in a (.net) client application. Anyone can decompile the app and use the key... And what happens after 50k requests? Who is gonna pay for it ^^

I see two options:

1) Provide the possibility to use your own API key (which the user registers himself) for the feature. The key is entered in the settings and stored localy on the PC. I am not sure how many people are gonna use it.

2) Use a service with limited / free tier, without the requirement of an API key like https://ip-api.com/
https://members.ip-api.com/#pricing --> The free endpoint is limited to 45 requests / minute

45 requests / minute should be OK in the most cases. I think this could also useful for the Traceroute feature #144.

Edit:
Maybe i still should contact the vendor of ip-api.com to see if there are any license problems if i integrate it into the app... even if NETworkManager is Open Source and not commerical.

**Comment by BornToBeRoot** [comment]
@Sahnreis  FYI: I will implement the Geo IP service (free endpoint): https://ip-api.com/

**Comment by BornToBeRoot** [comment]
I try to implement the https://ip-api.com/ in the next release. I close this PR since there were too many changes.

**Pull request closed without merging**
