### PR TITLE
Update Strings.sl-SI.resx

### PR DESCRIPTION
**Pull request by JadranR**
Updated 04.08.2022 Slovenian strings.
Best Regards,
Jadran

Fixes #{Replace this with the issue number}

**Please provide some details about this pull request:**
-
-
-

---

**By submitting this pull request, I confirm the following:**

- [ ] I have read and understood the [contributing guidelines](https://github.com/BornToBeRoot/NETworkManager/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/BornToBeRoot/NETworkManager/blob/main/CODE_OF_CONDUCT.md).
- [ ] I have have added my name, username or email to the [contributors](https://github.com/BornToBeRoot/NETworkManager/blob/main/Contributors.md) list or don't want to.
- [ ] The code or ressource is compatible with the [GNU General Public License v3.0](https://github.com/BornToBeRoot/NETworkManager/blob/main/LICENSE).

### CODE REVIEW

**Comment by BornToBeRoot** [comment]
Hi @JadranR and thanks for the contribution.

The translation is hosted on Transifex: https://www.transifex.com/BornToBeRoot/NETworkManager/
Can you make the changes there?
You need a Transifex account (login with GitHub) and join the Translation team for Slovenian.

---

I can't merge the file here because then we have a diff between transifex and github and it could be overwritten.

**Comment by JadranR** [comment]
Hi,

I have already made changes on Transifex (I have a Transifex account). But it is not nice that things are duplicated. Double work :(((

Best Regards,
Jadran

**Comment by BornToBeRoot** [comment]
Looks like the sync from transifex to github was broken after i switched the branch from master to main.

The sync is now working the translation was updated:
https://github.com/BornToBeRoot/NETworkManager/pull/1493

**Comment by JadranR** [comment]
Thanks!

V čet., 4. avg. 2022 22:10 je oseba BornToBeRoot ***@***.***>
napisala:

**Pull request closed without merging**
