### PR TITLE
Translation to Spanish

### PR DESCRIPTION
**Pull request by MS-PC**

### CODE REVIEW

**Comment by BornToBeRoot** [comment]
Thanks! I will take a look at this.

**Comment by BornToBeRoot** [comment]
If it is OK for you, i add your github username to the language selection.

image

**Comment by MS-PC** [comment]
Ok

**Comment by MS-PC** [comment]
Translate the last line: Ready
`<system:String x:Key="String_Header_ResolvePTR">Resolver PTR</system:String>`

**Comment by BornToBeRoot** [comment]
Thanks!

**Comment by BornToBeRoot** [comment]
See #115

**Comment by MS-PC** [comment]
Ok, thanks for adding it.

**Pull request closed without merging**
